/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package onlinegadget;

import java.awt.Image;
import java.awt.List;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author USER
 */
public class Categories extends javax.swing.JFrame {
ArrayList<Product> catagories;
String selected_brand;
String product_name_1,product_name_2,product_name_3,product_name_4;

Connection connect = null;
    Statement statement = null;
    PreparedStatement pStatement = null;
    ResultSet result = null;
OnlineDatabaseImplement ob=new OnlineDatabaseImplement();
int customer_id;

    /**
     * Creates new form Categories
     */
 public Categories()
 {
        initComponents();
        
 }
 public Categories(int id) {
        
     initComponents();
      customer_id=id;
     System.out.println("categories is= "+customer_id);
    
     System.out.println("id=" +id);
     connect=ConnectionConfiguration.setConnection();

     try{
         String query="SELECT * FROM brand";
         statement=connect.createStatement();
         result=statement.executeQuery(query);
         System.out.println("Successfull Query..");
         int i=0;
         while(result.next())
         {
           cat.addItem(result.getString("brand"));
         }

        result.close();


     }catch(Exception e){
         System.out.println("Error in Query..");
         e.printStackTrace();
 }

    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cat = new javax.swing.JComboBox<>();
        pic_1_name = new javax.swing.JLabel();
        pic_1_price = new javax.swing.JLabel();
        pic_2_name = new javax.swing.JLabel();
        pic_2_price = new javax.swing.JLabel();
        pic_3_name = new javax.swing.JLabel();
        pic_3_price = new javax.swing.JLabel();
        pic_4_name = new javax.swing.JLabel();
        pic_4_price = new javax.swing.JLabel();
        pic_1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        pic_2 = new javax.swing.JButton();
        pic_3 = new javax.swing.JButton();
        pic_4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Categoris");

        cat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catActionPerformed(evt);
            }
        });

        pic_1_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        pic_1_price.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        pic_2_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        pic_2_price.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        pic_3_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        pic_3_price.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        pic_4_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        pic_4_price.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        pic_1.setMinimumSize(new java.awt.Dimension(333, 456));
        pic_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pic_1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 153));
        jButton1.setText("See My Cart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        pic_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pic_2ActionPerformed(evt);
            }
        });

        pic_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pic_3ActionPerformed(evt);
            }
        });

        pic_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pic_4ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 102));
        jButton2.setText("Sign Out");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/onlinegadget/categoris.jpg"))); // NOI18N
        jLabel1.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(cat, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(570, 570, 570)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(pic_1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(pic_2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(pic_3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(pic_4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(pic_1_name, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(270, 270, 270)
                .addComponent(pic_3_name, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(pic_4_name, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(pic_1_price, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(pic_2_price, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(pic_3_price, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(662, 662, 662)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(pic_2_name, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(690, 690, 690)
                .addComponent(pic_4_price, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(145, 145, 145)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pic_1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pic_2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pic_3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pic_4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pic_1_name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pic_3_name, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(pic_4_name, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(pic_1_price, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(pic_2_price, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pic_3_price, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(500, 500, 500)
                .addComponent(pic_2_name, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(540, 540, 540)
                .addComponent(pic_4_price, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catActionPerformed
        // TODO add your handling code here:
        
        selected_brand=(String) cat.getSelectedItem();
        ResultSet res= ob.showImage(selected_brand);
         try {
             
         byte[] imageBytes;
         Image image;
         //while (res.next())
         //{
         res.next();
             imageBytes=res.getBytes(3);
             image = getToolkit().createImage(imageBytes);
             ImageIcon icon=new ImageIcon(image);
             product_name_1=res.getString(2);
             pic_1.setIcon(icon);
             pic_1_name.setText(res.getString(2));
             pic_1_price.setText(res.getString(5));
             
         res.next();
             imageBytes=res.getBytes(3);
             image = getToolkit().createImage(imageBytes);
             ImageIcon icon2=new ImageIcon(image);
               product_name_2=res.getString(2);
             pic_2.setIcon(icon2);
             pic_2_name.setText(res.getString(2));
             pic_2_price.setText(res.getString(5));
             
           res.next();
             imageBytes=res.getBytes(3);
             image = getToolkit().createImage(imageBytes);
             ImageIcon icon3=new ImageIcon(image);
               product_name_3=res.getString(2);
             pic_3.setIcon(icon3);
              pic_3_name.setText(res.getString(2));
             pic_3_price.setText(res.getString(5));
            res.next();
             imageBytes=res.getBytes(3);
             image = getToolkit().createImage(imageBytes);
             ImageIcon icon4=new ImageIcon(image);
             product_name_4=res.getString(2);
             pic_4.setIcon(icon4);
             pic_4_name.setText(res.getString(2));
             pic_4_price.setText(res.getString(5));
        
         
         
     } catch (SQLException ex) {
         //Logger.getLogger(image.class.getName()).log(Level.SEVERE, null, ex);
     }
        
    }//GEN-LAST:event_catActionPerformed

    private void pic_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pic_1ActionPerformed
         
        
          System.out.println("just before going to details= "+customer_id);
        new ProductDetails(customer_id,product_name_1).setVisible(true); 
        this.dispose();
    

        
    }//GEN-LAST:event_pic_1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      
      new CustomerCart(customer_id).setVisible(true);
      this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pic_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pic_2ActionPerformed
        // TODO add your handling code here:
         new ProductDetails(customer_id,product_name_2).setVisible(true); 
         this.dispose();
    }//GEN-LAST:event_pic_2ActionPerformed

    private void pic_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pic_3ActionPerformed
        // TODO add your handling code here:
         new ProductDetails(customer_id,product_name_3).setVisible(true);  
         this.dispose();
    }//GEN-LAST:event_pic_3ActionPerformed

    private void pic_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pic_4ActionPerformed
        // TODO add your handling code here:
         new ProductDetails(customer_id,product_name_4).setVisible(true);  
         this.dispose();
    }//GEN-LAST:event_pic_4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   new LogIn().setVisible(true);       
   this.dispose();
   // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Categories().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton pic_1;
    private javax.swing.JLabel pic_1_name;
    private javax.swing.JLabel pic_1_price;
    private javax.swing.JButton pic_2;
    private javax.swing.JLabel pic_2_name;
    private javax.swing.JLabel pic_2_price;
    private javax.swing.JButton pic_3;
    private javax.swing.JLabel pic_3_name;
    private javax.swing.JLabel pic_3_price;
    private javax.swing.JButton pic_4;
    private javax.swing.JLabel pic_4_name;
    private javax.swing.JLabel pic_4_price;
    // End of variables declaration//GEN-END:variables
}
