/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package onlinegadget;

import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static jdk.nashorn.internal.runtime.Debug.id;

/**
 *
 * @author USER
 */
public class ProductDetails extends javax.swing.JFrame {

    Connection connect = null;
    Statement statement = null;
    PreparedStatement pStatement = null;
    ResultSet result = null;
  OnlineDatabaseImplement ob=new OnlineDatabaseImplement();
  String address;
  int customer_id,product_id,total_price,p;
 
        
     /* Creates new form NewJFrame
     */
    public ProductDetails() {
        initComponents();
       
    }
 public ProductDetails(int id,String product_name) {
        initComponents();
        customer_id=id;
       System.out.println("product Deatails id= "+customer_id);
         addToCartPanel.setVisible(false);
         paymentPanel.setVisible(false);
       
        ResultSet res= ob.showDetails(product_name);
        try {
            
        
         
         byte[] imageBytes;
         Image image;
         //while (res.next())
         //{
         res.next();
             imageBytes=res.getBytes(3);
             image = getToolkit().createImage(imageBytes);
             ImageIcon icon=new ImageIcon(image);
             pic.setIcon(icon);
         product_id=res.getInt(1);
         p= res.getInt(5);
         name.setText(res.getString(2));
         price.setText(String.valueOf(p));
         
         cam.setText(res.getString(6));
         ram.setText(res.getString(7));
         display.setText(res.getString(10));
         os.setText(res.getString(8));
         processor.setText(res.getString(9));
         
           
         
         
         
        } catch (SQLException ex) {
         //Logger.getLogger(image.class.getName()).log(Level.SEVERE, null, ex);
    }
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        details = new javax.swing.JPanel();
        cam = new javax.swing.JLabel();
        ram = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        display = new javax.swing.JLabel();
        os = new javax.swing.JLabel();
        processor = new javax.swing.JLabel();
        pic = new javax.swing.JLabel();
        cart = new javax.swing.JButton();
        price = new javax.swing.JLabel();
        addToCartPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        quantity_tf = new javax.swing.JTextField();
        house_tf = new javax.swing.JTextField();
        block_tf = new javax.swing.JTextField();
        road_tf = new javax.swing.JTextField();
        city_tf = new javax.swing.JTextField();
        addToCartButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        paymentPanel = new javax.swing.JPanel();
        pType = new javax.swing.JComboBox<>();
        pin_tf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        addOrder = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tp = new javax.swing.JLabel();
        accountNo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Product Details");
        setPreferredSize(new java.awt.Dimension(900, 800));
        getContentPane().setLayout(null);

        details.setLayout(null);

        cam.setForeground(new java.awt.Color(255, 255, 255));
        details.add(cam);
        cam.setBounds(210, 180, 198, 33);

        ram.setForeground(new java.awt.Color(255, 255, 255));
        details.add(ram);
        ram.setBounds(220, 300, 198, 37);

        name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        details.add(name);
        name.setBounds(30, 440, 160, 33);

        display.setForeground(new java.awt.Color(255, 255, 255));
        details.add(display);
        display.setBounds(210, 220, 198, 40);

        os.setForeground(new java.awt.Color(255, 255, 255));
        details.add(os);
        os.setBounds(210, 260, 198, 36);

        processor.setForeground(new java.awt.Color(255, 255, 255));
        details.add(processor);
        processor.setBounds(210, 350, 198, 39);

        pic.setText("\n");
        details.add(pic);
        pic.setBounds(10, 100, 200, 320);

        cart.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cart.setForeground(new java.awt.Color(204, 0, 0));
        cart.setText("ADD TO CART");
        cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartActionPerformed(evt);
            }
        });
        details.add(cart);
        cart.setBounds(10, 530, 150, 40);

        price.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        price.setForeground(new java.awt.Color(255, 255, 255));
        details.add(price);
        price.setBounds(30, 480, 132, 38);

        addToCartPanel.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Quantity");
        addToCartPanel.add(jLabel1);
        jLabel1.setBounds(70, 20, 60, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("House");
        addToCartPanel.add(jLabel2);
        jLabel2.setBounds(70, 90, 50, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Block");
        addToCartPanel.add(jLabel3);
        jLabel3.setBounds(80, 170, 40, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Road");
        addToCartPanel.add(jLabel4);
        jLabel4.setBounds(80, 260, 60, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("City");
        addToCartPanel.add(jLabel5);
        jLabel5.setBounds(80, 340, 40, 30);

        quantity_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantity_tfActionPerformed(evt);
            }
        });
        addToCartPanel.add(quantity_tf);
        quantity_tf.setBounds(40, 50, 130, 40);
        addToCartPanel.add(house_tf);
        house_tf.setBounds(40, 120, 127, 40);
        addToCartPanel.add(block_tf);
        block_tf.setBounds(40, 210, 127, 40);
        addToCartPanel.add(road_tf);
        road_tf.setBounds(40, 300, 140, 40);
        addToCartPanel.add(city_tf);
        city_tf.setBounds(40, 380, 140, 40);

        addToCartButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addToCartButton.setForeground(new java.awt.Color(153, 0, 0));
        addToCartButton.setText("Done");
        addToCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartButtonActionPerformed(evt);
            }
        });
        addToCartPanel.add(addToCartButton);
        addToCartButton.setBounds(70, 433, 80, 40);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/onlinegadget/productdetails.jpg"))); // NOI18N
        addToCartPanel.add(jLabel12);
        jLabel12.setBounds(0, 0, 210, 510);

        details.add(addToCartPanel);
        addToCartPanel.setBounds(448, 40, 210, 500);

        back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(153, 0, 0));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        details.add(back);
        back.setBounds(10, 10, 90, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 0, 0));
        jButton1.setText("SignOut");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        details.add(jButton1);
        jButton1.setBounds(140, 10, 110, 30);

        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/onlinegadget/productdetails.jpg"))); // NOI18N
        details.add(jLabel9);
        jLabel9.setBounds(0, 0, 670, 590);

        getContentPane().add(details);
        details.setBounds(22, 16, 670, 590);

        paymentPanel.setLayout(null);

        pType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Bkash", "IFIC Mobile Banking"}));
        pType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pTypeActionPerformed(evt);
            }
        });
        paymentPanel.add(pType);
        pType.setBounds(30, 10, 140, 30);

        pin_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pin_tfActionPerformed(evt);
            }
        });
        paymentPanel.add(pin_tf);
        pin_tf.setBounds(40, 260, 100, 30);
        paymentPanel.add(jLabel6);
        jLabel6.setBounds(10, 90, 180, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Enter Pin:");
        paymentPanel.add(jLabel7);
        jLabel7.setBounds(50, 220, 90, 20);

        addOrder.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addOrder.setForeground(new java.awt.Color(153, 0, 0));
        addOrder.setText("Done");
        addOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrderActionPerformed(evt);
            }
        });
        paymentPanel.add(addOrder);
        addOrder.setBounds(60, 310, 70, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Total: ");
        paymentPanel.add(jLabel8);
        jLabel8.setBounds(80, 110, 50, 30);

        tp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tp.setForeground(new java.awt.Color(255, 255, 255));
        paymentPanel.add(tp);
        tp.setBounds(70, 150, 110, 30);

        accountNo.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        accountNo.setForeground(new java.awt.Color(255, 255, 255));
        paymentPanel.add(accountNo);
        accountNo.setBounds(10, 50, 180, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/onlinegadget/productdetails.jpg"))); // NOI18N
        paymentPanel.add(jLabel11);
        jLabel11.setBounds(-30, 0, 240, 350);

        getContentPane().add(paymentPanel);
        paymentPanel.setBounds(686, 115, 190, 350);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/onlinegadget/productdetails.jpg"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, -6, 900, 700);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartActionPerformed
        // TODO add your handling code here:
        addToCartPanel.setVisible(true);
          //cart.setVisible(false);
          paymentPanel.setVisible(false);
          
    }//GEN-LAST:event_cartActionPerformed

    private void addToCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartButtonActionPerformed
        // TODO add your handling code here:
        if(quantity_tf.getText().isEmpty() || house_tf.getText().isEmpty()||block_tf.getText().isEmpty()||road_tf.getText().isEmpty()||city_tf.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, " Some Fields are lying empty");
        }
        else
        {
        address="City :"+city_tf.getText()+"  "+"Road :"+"  "+road_tf.getText()+"  "+"Block  : "+block_tf.getText()+"  "+"House  :"+house_tf.getText();
        int quantity=(Integer.parseInt(quantity_tf.getText()));
        total_price=p*quantity;
        System.out.println("address= "+ address);
        ob.insertCart(product_id,quantity, customer_id, address);
        tp.setText(String.valueOf(total_price));
        paymentPanel.setVisible(true);
        addToCartPanel.setVisible(false);
        }
       
    }//GEN-LAST:event_addToCartButtonActionPerformed

    private void quantity_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantity_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantity_tfActionPerformed

    private void pin_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pin_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pin_tfActionPerformed

    private void pTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pTypeActionPerformed
       String paymentType=(String) pType.getSelectedItem();
       if(paymentType=="Bkash")
       {
           accountNo.setText("Merchant bKash 018********");
       }
       else if(paymentType=="IFIC Mobile Banking")
       {
           accountNo.setText("Merchant Account No 017********");
       }
    }//GEN-LAST:event_pTypeActionPerformed

    private void addOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrderActionPerformed
        try {
            // TODO add your handling code here:
            String payment_type=(String) pType.getSelectedItem();
            if(payment_type.isEmpty())
            {
                JOptionPane.showMessageDialog(null, " Please select a payment type");
            }
            else
            {
            int pin=(Integer.parseInt(pin_tf.getText()));
            
            ResultSet res=ob.getCartId();
            res.next();
            int cart_id=res.getInt(1);
            ob.insertOrder(cart_id,product_id,customer_id,total_price,payment_type,pin);
             JOptionPane.showMessageDialog(null, " Transaction Complete ");
            }
        } catch (SQLException ex) {
            Logger.getLogger(ProductDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_addOrderActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        new Categories(customer_id).setVisible(true);
        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  new LogIn().setVisible(true); 
  this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountNo;
    private javax.swing.JButton addOrder;
    private javax.swing.JButton addToCartButton;
    private javax.swing.JPanel addToCartPanel;
    private javax.swing.JButton back;
    private javax.swing.JTextField block_tf;
    private javax.swing.JLabel cam;
    private javax.swing.JButton cart;
    private javax.swing.JTextField city_tf;
    private javax.swing.JPanel details;
    private javax.swing.JLabel display;
    private javax.swing.JTextField house_tf;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel name;
    private javax.swing.JLabel os;
    private javax.swing.JComboBox<String> pType;
    private javax.swing.JPanel paymentPanel;
    private javax.swing.JLabel pic;
    private javax.swing.JTextField pin_tf;
    private javax.swing.JLabel price;
    private javax.swing.JLabel processor;
    private javax.swing.JTextField quantity_tf;
    private javax.swing.JLabel ram;
    private javax.swing.JTextField road_tf;
    private javax.swing.JLabel tp;
    // End of variables declaration//GEN-END:variables

    
}
