/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package onlinegadget;

import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class SignUp extends javax.swing.JFrame {
OnlineDatabaseImplement ob = new OnlineDatabaseImplement();
    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        name_tf = new javax.swing.JTextField();
        phone_tf = new javax.swing.JTextField();
        uName_tf = new javax.swing.JTextField();
        signUp = new javax.swing.JButton();
        pass_tf = new javax.swing.JPasswordField();
        cnfrmPass_tf = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign up");
        setBackground(new java.awt.Color(0, 153, 153));
        setPreferredSize(new java.awt.Dimension(900, 800));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Name:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 74, 70, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("Phone:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 430, 80, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("UserName:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 160, 90, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setText("Password:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(210, 240, 80, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setText("Confirm Password:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(150, 330, 160, 40);
        getContentPane().add(name_tf);
        name_tf.setBounds(340, 77, 280, 40);
        getContentPane().add(phone_tf);
        phone_tf.setBounds(340, 430, 280, 40);
        getContentPane().add(uName_tf);
        uName_tf.setBounds(340, 160, 280, 40);

        signUp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        signUp.setForeground(new java.awt.Color(102, 0, 102));
        signUp.setText("Sign Up");
        signUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpActionPerformed(evt);
            }
        });
        getContentPane().add(signUp);
        signUp.setBounds(500, 550, 110, 40);
        getContentPane().add(pass_tf);
        pass_tf.setBounds(340, 240, 280, 40);
        getContentPane().add(cnfrmPass_tf);
        cnfrmPass_tf.setBounds(340, 330, 280, 40);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 550, 110, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/onlinegadget/signup.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 900, 700);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpActionPerformed
        // TODO add your handling code here:
        String name ,phone,username,password;
        name=name_tf.getText();
        phone=phone_tf.getText();
        username=uName_tf.getText();
        password=pass_tf.getText();
        if(name_tf.getText().isEmpty()|| phone_tf.getText().isEmpty()||uName_tf.getText().isEmpty()|| pass_tf.getText().isEmpty()||cnfrmPass_tf.getText().isEmpty() )
        {
            JOptionPane.showMessageDialog(null, " Some Fields are lying empty");
        }
        else if(!pass_tf.getText().equals(cnfrmPass_tf.getText()))
        {
             JOptionPane.showMessageDialog(null, " Password Doesn't Match");
             pass_tf.setText(null);
             cnfrmPass_tf.setText(null);

        }
        else
        {
        ob.signup(name,phone,username,password);
        JOptionPane.showMessageDialog(null, " Successfull");
         new LogIn().setVisible(true);
         this.dispose();
        }
        //new LogIn().setVisible(true);
    }//GEN-LAST:event_signUpActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new LogIn().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField cnfrmPass_tf;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField name_tf;
    private javax.swing.JPasswordField pass_tf;
    private javax.swing.JTextField phone_tf;
    private javax.swing.JButton signUp;
    private javax.swing.JTextField uName_tf;
    // End of variables declaration//GEN-END:variables
}
